steps:
- name: 'docker'
  args: ['build', '.', '-f', 'Dockerfile.build', '-t', 'builder']
- name: 'builder'
  args: ['/build.sh']
- name: 'docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/centos7:$_TAG_NAME']
images: ['gcr.io/$PROJECT_ID/centos7:$_TAG_NAME']
