# All items surrounded by %% are variables to be replaced with real values.
# gcr.io/google-appengine: The repository to push debian to, e.g. gcr.io/myproject
# 2016-09-19: What the tag the image with, e.g. latest
# jessie: The version of debian to build, e.g. jessie
# 8: The version number associated with the jessie string, e.g. 8 for jessie
steps:
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=gcr.io/google-appengine/mkdebootstrap:jessie'
                - 'mkdebootstrap/'
        - name: gcr.io/google-appengine/mkdebootstrap:jessie
          args:
                - '-d'
                - '/workspace'
                - 'debootstrap'
                - '--variant=minbase'
                - 'jessie'
                - 'http://httpredir.debian.org/debian'
        - name: gcr.io/cloud-builders/docker
          args:
                - 'build'
                - '--tag=gcr.io/google-appengine/debian8:2016-09-19'
                - '.'
images: ['gcr.io/google-appengine/mkdebootstrap:jessie', 'gcr.io/google-appengine/debian8:2016-09-19']
